"""Pydantic models for angle tracking, exercise corrections, and streaming payloads."""

from pydantic import BaseModel, Field


class JointAngle(BaseModel):
    """A single joint's signed angle measurement.

    Positive angles indicate the end limb is clockwise from the base limb
    (in screen coordinates); negative angles indicate counter-clockwise.
    """

    joint_name: str = Field(description="Human-readable joint name (e.g. 'Right Elbow')")
    angle_degrees: float = Field(
        description="Signed angle in degrees (-180 to +180). "
        "Positive = clockwise from base, negative = counter-clockwise."
    )
    base_landmark: str = Field(description="Name of the base/reference landmark")
    vertex_landmark: str = Field(description="Name of the vertex (joint center) landmark")
    end_landmark: str = Field(description="Name of the end landmark")


class ExerciseCorrection(BaseModel):
    """Real-time feedback for a specific joint during an exercise.

    Generated by comparing the current angle to the target angle for
    the active exercise.
    """

    joint_name: str = Field(description="Joint this correction applies to")
    current_angle: float = Field(description="Current measured angle (degrees)")
    target_angle: float = Field(description="Desired target angle (degrees)")
    deviation: float = Field(
        description="Signed deviation: current - target (degrees). "
        "Positive = over-extended, negative = under-extended."
    )
    message: str = Field(description="Human-readable correction instruction")
    severity: str = Field(
        description="Severity level: 'info', 'warning', or 'critical'",
        pattern="^(info|warning|critical)$",
    )


class TrackingFrame(BaseModel):
    """Top-level payload streamed to the frontend for each processed frame.

    Contains all joint angle measurements and any active exercise corrections.
    """

    frame_number: int = Field(description="Sequential frame counter")
    timestamp_ms: float = Field(description="Frame timestamp in milliseconds")
    joint_angles: list[JointAngle] = Field(
        default_factory=list,
        description="Signed angle measurements for all tracked joints",
    )
    corrections: list[ExerciseCorrection] = Field(
        default_factory=list,
        description="Active exercise corrections/feedback",
    )
    pose_detected: bool = Field(
        default=False,
        description="Whether a valid pose was detected in this frame",
    )
